#!/usr/bin/env python3
import argparse

def main():
    parser = argparse.ArgumentParser(description="File Transfer Server")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("-v", "--verbose", action="store_true", help="increase output verbosity")
    group.add_argument("-q", "--quiet", action="store_true", help="decrease output verbosity")
    parser.add_argument("-H", "--host", required=True, help="service IP address")
    parser.add_argument("-p", "--port", type=int, required=True, help="service port")
    parser.add_argument("-s", "--storage", required=True, help="storage dir path")
    args = parser.parse_args()

if __name__ == "__main__":
    main()
