#!/usr/bin/env python3
import argparse
import socket


def crear socket(host, port):
    
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind((host, port))
    sock.listen(5)
    return sock


def main():
    parser = argparse.ArgumentParser(description="File Transfer Server")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("-v", "--verbose", action="store_true", help="increase output verbosity")
    group.add_argument("-q", "--quiet", action="store_true", help="decrease output verbosity")
    parser.add_argument("-H", "--host", type=str, default="127.0.0.1", help="IP al que se quiere conectar")
    parser.add_argument("-p", "--port", type=int, default= 5005, help="Puerto al que se quiere conectar")
    

    args = parser.parse_args()

    socket_listening = crear_socket(args.host, args.port)
    
    while True:
  
        data, addr = socket.recvfrom(1024)   
        packet = Packet.decode(data)

        if packet.opcode == Packet.OP_START:

            socketUDP = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

            session = session(server_socket=socketUDP, client_socket=addr, packet=packet, args=args)
            session.start_session()
            
        elif packet.opcode == Packet.OP_DATA:
            session.update_session(packet)



"""

            print(f"Handshake iniciado desde {addr}")
            ack_packet = handshake_ack(packet.seq_num)
            socket.sendto(ack_packet.encode(), addr)
            print(f"Enviando ACK al cliente {addr}")
        elif packet.opcode == Packet.OP_DATA:
            print(f"Recibiendo datos del cliente {addr}")
            # Aquí se procesarían los datos recibidos
            ack_packet = handshake_ack(packet.seq_num)
            socket.sendto(ack_packet.encode(), addr)
            print(f"Enviando ACK al cliente {addr}")
"""








if __name__ == "__main__":
    main()
