#!/usr/bin/env python3
import argparse
from lib.file_transfer_server import FileTransferServer

def main():
    parser = argparse.ArgumentParser(description="File Transfer Server")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("-v", "--verbose", action="store_true", help="increase output verbosity")
    group.add_argument("-q", "--quiet", action="store_true", help="decrease output verbosity")
    parser.add_argument("-H", "--host", type=str, default="127.0.0.1", help="IP al que se quiere conectar")
    parser.add_argument("-p", "--port", type=int, default= 5005, help="Puerto al que se quiere conectar")
    
    args = parser.parse_args()

    server = FileTransferServer(host=args.host, port=args.port)

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.stop()



"""

            print(f"Handshake iniciado desde {addr}")
            ack_packet = handshake_ack(packet.seq_num)
            socket.sendto(ack_packet.encode(), addr)
            print(f"Enviando ACK al cliente {addr}")
        elif packet.opcode == Packet.OP_DATA:
            print(f"Recibiendo datos del cliente {addr}")
            # Aquí se procesarían los datos recibidos
            ack_packet = handshake_ack(packet.seq_num)
            socket.sendto(ack_packet.encode(), addr)
            print(f"Enviando ACK al cliente {addr}")
"""








if __name__ == "__main__":
    main()
